# Site settings
title:          Wallace Lim
description:    "Personal website"
url:            "wallace-lim.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Wallace Lim
  url:          https://wallace-lim.github.io
  email:        wallace.xy.lim@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /posts/:year/:month/:day/:title
paginate:       5
paginate_path: "/blog/page:num"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale